In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
%cd drive/MyDrive

/content/drive/MyDrive

In [ ]:
!ls

 20221029-053129_annot_df_sorted_subclassed_slide_no_2.csv
 20221030-011825_annot_df_sorted_subclassed_MLFs_32_slide_no_2.csv
'Colab Notebooks'
 dog_dataset
'Getting started.pdf'
 hymenoptera_data
 LectureNotes01.pdf
 LectureNotes02.pdf
 LectureNotes03.pdf
 LectureNotes04.pdf
 LectureNotes05.pdf
 LectureNotes06.pdf
 LectureNotes07.pdf
 LectureNotes08.pdf
 LectureNotes09.pdf
 MITOS_WSI_CMC
 week-10-nlp

In [5]:
import pandas as pd
data1 = pd.read_csv('20221029-053129_annot_df_sorted_subclassed_slide_no_2.csv')
data2 = pd.read_csv('20221030-011825_annot_df_sorted_subclassed_MLFs_32_slide_no_2.csv')
data = pd.concat([data1, data2])

In [6]:
!pwd
%cd ..

/content/drive/MyDrive
/content/drive

In [7]:
data.head()

,Unnamed: 0,key,uid,ctr,coord,lbl,guid,subcl
0,134,144,144,"[39154, 38931]",[[39129 38906]\r\n [39179 38956]],2,55769705-b5df-4669-bd4a-6abb782c05e9,4
1,110,116,116,"[41841, 35854]",[[41816 35829]\r\n [41866 35879]],2,37da286e-c719-4e2e-8c28-5106279c8745,7
2,104,109,109,"[43709, 35008]",[[43684 34983]\r\n [43734 35033]],2,aac4e2fa-c1ad-42f4-b139-c9b7d5b3696b,7
3,188,1396,1396,"[14790, 34067]",[[14765 34042]\r\n [14815 34092]],2,47118562-d433-49d2-9c72-b0c1fa5242ea,4
4,101,106,106,"[23996, 35202]",[[23971 35177]\r\n [24021 35227]],2,d819ba1a-ff85-40bd-8e39-faf42117c8a4,7

In [8]:
data.tail()

,Unnamed: 0,key,uid,ctr,coord,lbl,guid,subcl
263,158,170,170,"[29550, 50913]",[[29525 50888]\r\n [29575 50938]],2,1390e642-0f94-46f0-8c17-e779b9e14365,42
264,157,169,169,"[32990, 50488]",[[32965 50463]\r\n [33015 50513]],2,9ece6b80-00c4-41a4-98cc-605fcb66b698,42
265,156,168,168,"[33107, 50474]",[[33082 50449]\r\n [33132 50499]],2,b3b87c92-64f6-4133-9ee9-6bbb469fa56d,42
266,97,102,102,"[10910, 35820]",[[10885 35795]\r\n [10935 35845]],2,2c7ad1c8-1293-4a4b-b651-9335d438fbb3,42
267,133,143,143,"[37772, 39661]",[[37747 39636]\r\n [37797 39686]],2,1fd1dc45-45b5-4efa-a593-779cdd166ed3,42

In [9]:
data['subcl'] = data['subcl'].replace(42,9)
data_filtered = data[data['subcl'] != 9]

In [10]:
data_filtered.head()

,Unnamed: 0,key,uid,ctr,coord,lbl,guid,subcl
0,134,144,144,"[39154, 38931]",[[39129 38906]\r\n [39179 38956]],2,55769705-b5df-4669-bd4a-6abb782c05e9,4
1,110,116,116,"[41841, 35854]",[[41816 35829]\r\n [41866 35879]],2,37da286e-c719-4e2e-8c28-5106279c8745,7
2,104,109,109,"[43709, 35008]",[[43684 34983]\r\n [43734 35033]],2,aac4e2fa-c1ad-42f4-b139-c9b7d5b3696b,7
3,188,1396,1396,"[14790, 34067]",[[14765 34042]\r\n [14815 34092]],2,47118562-d433-49d2-9c72-b0c1fa5242ea,4
4,101,106,106,"[23996, 35202]",[[23971 35177]\r\n [24021 35227]],2,d819ba1a-ff85-40bd-8e39-faf42117c8a4,7

In [11]:
data_filtered.shape
data = data_filtered.copy()
data = data[data['subcl'] != 0]

The center specified in the CSV is a String.  We have to convert it to a list of int.

In [12]:
i = 0
ctrlist = []
while (i<len(data)):
  ctr = data.iloc[i][3]
  ctrcoord = []
  newcoord = ""
  for elt in ctr:
    if (   (elt != '[') and (elt != ']') and (elt != ',') and (elt != ' ')   ) :
       newcoord = newcoord + elt
    if  (elt == ","):
       ctrcoord.append(int(newcoord))
       newcoord = ""
  ctrcoord.append(int(newcoord.strip()))
  ctrlist.append(ctrcoord)
  i = i + 1
data.head()
data['ctr'] = ctrlist

In [13]:
data.tail()

,Unnamed: 0,key,uid,ctr,coord,lbl,guid,subcl
29,121,127,127,"[8524, 37594]",[[ 8499 37569]\r\n [ 8549 37619]],1,8f8a590d-7692-489d-856e-710342a7a159,8
30,122,128,128,"[8652, 37635]",[[ 8627 37610]\r\n [ 8677 37660]],1,d33324aa-da48-43c6-ae0c-faf686cfb04d,8
31,126,134,134,"[22826, 39227]",[[22801 39202]\r\n [22851 39252]],1,c8c272d3-8d93-46ad-8902-376a8bfc16aa,8
32,128,137,137,"[38821, 38630]",[[38796 38605]\r\n [38846 38655]],1,f5bcc540-bd3a-412f-810d-ae37ded762f2,8
33,130,139,139,"[35000, 39510]",[[34975 39485]\r\n [35025 39535]],1,35fe13f9-21e8-44d7-8e18-516d13fd77af,8

In [ ]:
#data.drop('ctrasint', axis=1)

KeyError: ignored

In [14]:
centers = data[['guid','ctr','subcl']]

In [15]:
centers.head()
int(data.iloc[1][3][1])

35854

Patch Selection

In [16]:
!ls
%cd MyDrive

MyDrive
/content/drive/MyDrive

In [17]:
%cd MITOS_WSI_CMC/databases

/content/drive/MyDrive/MITOS_WSI_CMC/databases

In [18]:
%cd WSI

[Errno 2] No such file or directory: 'WSI'
/content/drive/MyDrive/MITOS_WSI_CMC/databases

In [ ]:
!mkdir subclass_patches

In [ ]:
!ls

databaseStatistics.ipynb
Data_CMC-f
MITOS_WSI_CMC_COADEL_TR.sqlite
MITOS_WSI_CMC_CODAEL_TR_ROI.sqlite
MITOS_WSI_CMC_MEL.sqlite
MITOS_WSI_CMC_ODAEL_TR.sqlite
subclass_patches
TUPAC_alternativeLabels_augmented_training.sqlite
TUPAC.sqlite
TUPAC_stitched.sqlite

In [ ]:
#Now, we extract patches into .png files.

In [19]:
!pip install SlideRunner
!sudo apt-get install openslide-tools	
!sudo apt-get install python3-openslide

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: SlideRunner in /usr/local/lib/python3.7/dist-packages (2.0)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (3.2.2)
Requirement already satisfied: PyQt5 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (5.15.7)
Requirement already satisfied: opencv-python>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (4.6.0.66)
Requirement already satisfied: shapely>=1.6.4 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (1.8.5.post1)
Requirement already satisfied: pydicom>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (2.3.0)
Requirement already satisfied: rollbar>=0.14 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (0.16.3)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (1.21.6)
Requirement already satisfied: openslide-python>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from SlideRunner) (1.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->SlideRunner) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->SlideRunner) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->SlideRunner) (3.0.9)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->SlideRunner) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->SlideRunner) (4.1.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from openslide-python>=1.1.1->SlideRunner) (9.3.0)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in /usr/local/lib/python3.7/dist-packages (from PyQt5->SlideRunner) (12.11.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in /usr/local/lib/python3.7/dist-packages (from PyQt5->SlideRunner) (5.15.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=2.0.0->SlideRunner) (1.15.0)
Requirement already satisfied: requests>=0.12.1 in /usr/local/lib/python3.7/dist-packages (from rollbar>=0.14->SlideRunner) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=0.12.1->rollbar>=0.14->SlideRunner) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=0.12.1->rollbar>=0.14->SlideRunner) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=0.12.1->rollbar>=0.14->SlideRunner) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=0.12.1->rollbar>=0.14->SlideRunner) (1.24.3)
Reading package lists... Done
Building dependency tree
Reading state information... Done
openslide-tools is already the newest version (3.4.1+dfsg-2).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-openslide is already the newest version (1.1.1-2ubuntu4).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

In [20]:
!pip install sliderunner-dataaccess

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sliderunner-dataaccess in /usr/local/lib/python3.7/dist-packages (1.0.9)
Requirement already satisfied: nibabel>=3.1.1 in /usr/local/lib/python3.7/dist-packages (from sliderunner-dataaccess) (4.0.2)
Requirement already satisfied: pillow>=8.0.1 in /usr/local/lib/python3.7/dist-packages (from sliderunner-dataaccess) (9.3.0)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from sliderunner-dataaccess) (3.2.2)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.7/dist-packages (from sliderunner-dataaccess) (1.21.6)
Requirement already satisfied: openslide-python>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from sliderunner-dataaccess) (1.2.0)
Requirement already satisfied: pydicom>=2.1.2 in /usr/local/lib/python3.7/dist-packages (from sliderunner-dataaccess) (2.3.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->sliderunner-dataaccess) (1.4.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->sliderunner-dataaccess) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->sliderunner-dataaccess) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->sliderunner-dataaccess) (0.11.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->sliderunner-dataaccess) (4.1.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from nibabel>=3.1.1->sliderunner-dataaccess) (57.4.0)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.7/dist-packages (from nibabel>=3.1.1->sliderunner-dataaccess) (21.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=2.0.0->sliderunner-dataaccess) (1.15.0)

In [21]:
!pip install requests-toolbelt
!pip install EXCAT-Sync

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests-toolbelt in /usr/local/lib/python3.7/dist-packages (0.10.1)
Requirement already satisfied: requests<3.0.0,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from requests-toolbelt) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (2022.9.24)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: EXCAT-Sync in /usr/local/lib/python3.7/dist-packages (0.0.34)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from EXCAT-Sync) (2.23.0)
Requirement already satisfied: locust==1.1.0 in /usr/local/lib/python3.7/dist-packages (from EXCAT-Sync) (1.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from EXCAT-Sync) (4.64.1)
Requirement already satisfied: requests-toolbelt in /usr/local/lib/python3.7/dist-packages (from EXCAT-Sync) (0.10.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/dist-packages (from EXCAT-Sync) (9.3.0)
Requirement already satisfied: psutil>=5.6.7 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (5.9.4)
Requirement already satisfied: flask>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (1.1.4)
Requirement already satisfied: pyzmq>=16.0.2 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (23.2.1)
Requirement already satisfied: geventhttpclient>=1.4.2 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (2.0.8)
Requirement already satisfied: gevent>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (22.10.2)
Requirement already satisfied: ConfigArgParse>=1.0 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (1.5.3)
Requirement already satisfied: msgpack>=0.6.2 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (1.0.4)
Requirement already satisfied: Flask-BasicAuth>=0.2.0 in /usr/local/lib/python3.7/dist-packages (from locust==1.1.0->EXCAT-Sync) (0.2.0)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from flask>=1.1.2->locust==1.1.0->EXCAT-Sync) (1.0.1)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from flask>=1.1.2->locust==1.1.0->EXCAT-Sync) (7.1.2)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from flask>=1.1.2->locust==1.1.0->EXCAT-Sync) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from flask>=1.1.2->locust==1.1.0->EXCAT-Sync) (1.1.0)
Requirement already satisfied: greenlet>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from gevent>=1.5.0->locust==1.1.0->EXCAT-Sync) (2.0.1)
Requirement already satisfied: zope.event in /usr/local/lib/python3.7/dist-packages (from gevent>=1.5.0->locust==1.1.0->EXCAT-Sync) (4.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from gevent>=1.5.0->locust==1.1.0->EXCAT-Sync) (57.4.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.7/dist-packages (from gevent>=1.5.0->locust==1.1.0->EXCAT-Sync) (5.5.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from geventhttpclient>=1.4.2->locust==1.1.0->EXCAT-Sync) (1.15.0)
Requirement already satisfied: brotli in /usr/local/lib/python3.7/dist-packages (from geventhttpclient>=1.4.2->locust==1.1.0->EXCAT-Sync) (1.0.9)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from geventhttpclient>=1.4.2->locust==1.1.0->EXCAT-Sync) (2022.9.24)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->flask>=1.1.2->locust==1.1.0->EXCAT-Sync) (2.0.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->EXCAT-Sync) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->EXCAT-Sync) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->EXCAT-Sync) (3.0.4)

In [22]:
%cd MITOS_WSI_CMC/

[Errno 2] No such file or directory: 'MITOS_WSI_CMC/'
/content/drive/MyDrive/MITOS_WSI_CMC/databases

In [21]:
!pwd

/content/drive/MyDrive/MITOS_WSI_CMC/databases

In [23]:
!pwd
%cd databases

/content/drive/MyDrive/MITOS_WSI_CMC/databases
[Errno 2] No such file or directory: 'databases'
/content/drive/MyDrive/MITOS_WSI_CMC/databases

In [24]:
#Code refactored from ExtractPatches.py

import numpy as np 
import SlideRunner.general.dependencies
from SlideRunner.dataAccess.database import Database
from SlideRunner.dataAccess.annotations import *
import os
import openslide
import sqlite3
import cv2
import sys

DB = Database()

vp = ViewingProfile()
vp.majorityClassVote=True

cm=np.zeros((7,7))
if len(sys.argv)<2:
    print('Synopsis: ',sys.argv[0],'<valrun>')
    sys.exit()
threshold = 5

disagreedclass = 0
agreedclass = 0
basepath='../WSI/'
patchSize=50

os.system('mkdir -p Data_CMC%s' % sys.argv[1])

dirs = ['Mitosis', 'Nonmitosis']
for k in dirs:
    os.system('mkdir -p Data_CMC%s/train/%s' % (sys.argv[1],k))
    os.system('mkdir -p Data_CMC%s/test/%s' % (sys.argv[1],k))

def listOfSlides(DB):
    DB.execute('SELECT uid,filename from Slides')
    return DB.fetchall()

slidelist_test_1 = ['18','3', '22','10','15','21','14']
slidelist_test_2 = ['1', '20','17','5', '2', '11','16']
slidelist_test_3 = ['12','13','7', '19','8', '6', '9']

test_slides = { '1': slidelist_test_1,
                '2': slidelist_test_2,
                '3': slidelist_test_3}

from os import system
DB.open('../databases/MITOS_WSI_CMC_MEL.sqlite')  #Change the original code here to use MEL data

j = 1
while j<2:
    slideid = 2
    filename = 'a8773be388e12df89edd.svs'
    DB.loadIntoMemory(slideid)
    slide=openslide.open_slide(basepath+filename)
    i = 0
    while(i<len(data)):   #FSL annotations should be used here
        anno = data['subcl']
        print(data.iloc[i])
        coordinate = data.iloc[i]['ctr']
        coord_x = coordinate[0]
        print(coord_x)
        coord_y = coordinate[1]
        lu_x = int(coord_x - int(patchSize/2))
        lu_y = int(coord_y - int(patchSize/2))
        img = np.array(slide.read_region(location=(lu_x, lu_y), level=0, size=(patchSize, patchSize)))
        img = cv2.cvtColor(img, cv2.COLOR_RGBA2BGR)
        istest = 'allslides/' 
        if (data.iloc[i][5] == 2):
            cv2.imwrite(str(i) + '.png' , img)
            #system(f'ln -s ../../../images/Mitosis/{k}.png Data_CMC{sys.argv[1]}/'+istest+'Mitosis.png' %k)

        if (data.iloc[i][5]==1):
            cv2.imwrite(str(i) + '.png', img)
            #system(f'ln -s ../../../images/Nonmitosis/{k}.png Data_CMC{sys.argv[1]}/'+istest+'Nonmitosis.png' %k)
        i = i + 1
    j = j + 1


"""
    for k in DB.annotations.keys():   #FSL annotations should be used here

        anno = DB.annotations[k]

        if anno.deleted or anno.annotationType != AnnotationType.SPOT:
            continue
        coord_x = anno.x1
        coord_y = anno.y1

        lu_x = int(coord_x - int(patchSize/2))
        lu_y = int(coord_y - int(patchSize/2))
        img = np.array(slide.read_region(location=(lu_x, lu_y), level=0, size=(patchSize, patchSize)))
        img = cv2.cvtColor(img, cv2.COLOR_RGBA2BGR)


        istest = 'train/' if str(slideid) not in test_slides[sys.argv[1]] else 'test/'
        if (anno.agreedClass ==2):
            cv2.imwrite('images/Mitosis/%d.png' % k, img)
            system(f'ln -s ../../../images/Mitosis/{k}.png Data_CMC{sys.argv[1]}/'+istest+'Mitosis/%d.png' %k)

        if (anno.agreedClass==1):
            cv2.imwrite('images/Nonmitosis/%d.png' % k, img)
            system(f'ln -s ../../../images/Nonmitosis/{k}.png Data_CMC{sys.argv[1]}/'+istest+'Nonmitosis/%d.png' %k)
            """

Unnamed: 0                                     134
key                                            144
uid                                            144
ctr                                 [39154, 38931]
coord            [[39129 38906]\r\n [39179 38956]]
lbl                                              2
guid          55769705-b5df-4669-bd4a-6abb782c05e9
subcl                                            4
Name: 0, dtype: object
39154
Unnamed: 0                                     110
key                                            116
uid                                            116
ctr                                 [41841, 35854]
coord            [[41816 35829]\r\n [41866 35879]]
lbl                                              2
guid          37da286e-c719-4e2e-8c28-5106279c8745
subcl                                            7
Name: 1, dtype: object
41841
Unnamed: 0                                     104
key                                            109
uid                                            109
ctr                                 [43709, 35008]
coord            [[43684 34983]\r\n [43734 35033]]
lbl                                              2
guid          aac4e2fa-c1ad-42f4-b139-c9b7d5b3696b
subcl                                            7
Name: 2, dtype: object
43709
Unnamed: 0                                     188
key                                           1396
uid                                           1396
ctr                                 [14790, 34067]
coord            [[14765 34042]\r\n [14815 34092]]
lbl                                              2
guid          47118562-d433-49d2-9c72-b0c1fa5242ea
subcl                                            4
Name: 3, dtype: object
14790
Unnamed: 0                                     101
key                                            106
uid                                            106
ctr                                 [23996, 35202]
coord            [[23971 35177]\r\n [24021 35227]]
lbl                                              2
guid          d819ba1a-ff85-40bd-8e39-faf42117c8a4
subcl                                            7
Name: 4, dtype: object
23996
Unnamed: 0                                     100
key                                            105
uid                                            105
ctr                                 [14293, 34679]
coord            [[14268 34654]\r\n [14318 34704]]
lbl                                              2
guid          8d2b7434-407e-4d3f-b61b-fceb0b27d5c6
subcl                                            7
Name: 5, dtype: object
14293
Unnamed: 0                                      99
key                                            104
uid                                            104
ctr                                 [11166, 35831]
coord            [[11141 35806]\r\n [11191 35856]]
lbl                                              2
guid          7e538efe-7c4c-4f7b-8f22-c10d61c27366
subcl                                            7
Name: 6, dtype: object
11166
Unnamed: 0                                      98
key                                            103
uid                                            103
ctr                                 [11153, 35690]
coord            [[11128 35665]\r\n [11178 35715]]
lbl                                              2
guid          6a856710-6ab3-4807-99cb-659e8b9d6ae3
subcl                                            7
Name: 7, dtype: object
11153
Unnamed: 0                                      97
key                                            102
uid                                            102
ctr                                 [10910, 35820]
coord            [[10885 35795]\r\n [10935 35845]]
lbl                                              2
guid          2c7ad1c8-1293-4a4b-b651-9335d438fbb3
subcl                                            7
Name: 8, dtype: object
10910
Unnamed: 0                                      94
key                                             99
uid                                             99
ctr                                  [7746, 34679]
coord            [[ 7721 34654]\r\n [ 7771 34704]]
lbl                                              2
guid          0b1511e8-a58e-4e54-9265-65ac68d9c5de
subcl                                            6
Name: 9, dtype: object
7746
Unnamed: 0                                      91
key                                             96
uid                                             96
ctr                                  [4892, 34378]
coord            [[ 4867 34353]\r\n [ 4917 34403]]
lbl                                              2
guid          05a5f63f-5074-4dc5-8539-eedb463da025
subcl                                            7
Name: 11, dtype: object
4892
Unnamed: 0                                      90
key                                             95
uid                                             95
ctr                                 [17290, 33414]
coord            [[17265 33389]\r\n [17315 33439]]
lbl                                              2
guid          1acb96aa-996b-4a04-b0d9-f48cdd4a0934
subcl                                            7
Name: 12, dtype: object
17290
Unnamed: 0                                      89
key                                             94
uid                                             94
ctr                                 [17556, 33193]
coord            [[17531 33168]\r\n [17581 33218]]
lbl                                              2
guid          645bfc04-1694-4776-a067-5dcc21e3f3f5
subcl                                            7
Name: 13, dtype: object
17556
Unnamed: 0                                      88
key                                             92
uid                                             92
ctr                                  [8295, 33703]
coord            [[ 8270 33678]\r\n [ 8320 33728]]
lbl                                              2
guid          4e1f47a8-19c1-4429-b27a-cc10cf0499cb
subcl                                            7
Name: 14, dtype: object
8295
Unnamed: 0                                      86
key                                             90
uid                                             90
ctr                                 [43235, 32841]
coord            [[43210 32816]\r\n [43260 32866]]
lbl                                              2
guid          19fdcfde-7cfe-4371-8aaa-cad32fa03fc6
subcl                                            7
Name: 15, dtype: object
43235
Unnamed: 0                                      82
key                                             86
uid                                             86
ctr                                 [14480, 32759]
coord            [[14455 32734]\r\n [14505 32784]]
lbl                                              2
guid          2dfa3b78-4285-49f3-b0cd-ac9581c885df
subcl                                            7
Name: 17, dtype: object
14480
Unnamed: 0                                     158
key                                            170
uid                                            170
ctr                                 [29550, 50913]
coord            [[29525 50888]\r\n [29575 50938]]
lbl                                              2
guid          1390e642-0f94-46f0-8c17-e779b9e14365
subcl                                            7
Name: 18, dtype: object
29550
Unnamed: 0                                     198
key                                           1406
uid                                           1406
ctr                                  [5335, 36590]
coord            [[ 5310 36565]\r\n [ 5360 36615]]
lbl                                              2
guid          1081bb7d-f589-4bcb-9870-7ec4f9304baf
subcl                                            7
Name: 19, dtype: object
5335
Unnamed: 0                                      77
key                                             80
uid                                             80
ctr                                 [12988, 32700]
coord            [[12963 32675]\r\n [13013 32725]]
lbl                                              2
guid          a18292f0-fc81-401b-be4d-a4542618e4c4
subcl                                            7
Name: 20, dtype: object
12988
Unnamed: 0                                      76
key                                             79
uid                                             79
ctr                                 [13176, 32652]
coord            [[13151 32627]\r\n [13201 32677]]
lbl                                              2
guid          b11ab96c-8c8e-41ac-8e23-245b1a90595f
subcl                                            4
Name: 21, dtype: object
13176
Unnamed: 0                                     199
key                                           1407
uid                                           1407
ctr                                  [5418, 36594]
coord            [[ 5393 36569]\r\n [ 5443 36619]]
lbl                                              2
guid          fc3e1c81-4786-4c6d-bb40-8679ac3952a3
subcl                                            4
Name: 22, dtype: object
5418
Unnamed: 0                                     201
key                                           1409
uid                                           1409
ctr                                 [10807, 37109]
coord            [[10782 37084]\r\n [10832 37134]]
lbl                                              2
guid          e0a9f236-f277-4011-9b3b-f8972cd66503
subcl                                            7
Name: 23, dtype: object
10807
Unnamed: 0                                      72
key                                             75
uid                                             75
ctr                                  [7381, 31587]
coord            [[ 7356 31562]\r\n [ 7406 31612]]
lbl                                              2
guid          8245fdbf-a30d-4e8f-adcb-fcce63750220
subcl                                            7
Name: 24, dtype: object
7381
Unnamed: 0                                      71
key                                             74
uid                                             74
ctr                                  [7640, 31709]
coord            [[ 7615 31684]\r\n [ 7665 31734]]
lbl                                              2
guid          045427d7-af12-4fc3-ba09-1c9a96476870
subcl                                            4
Name: 25, dtype: object
7640
Unnamed: 0                                      66
key                                             69
uid                                             69
ctr                                 [17102, 30944]
coord            [[17077 30919]\r\n [17127 30969]]
lbl                                              2
guid          33f9b8a3-a61d-44cd-9cac-b8c555de1c12
subcl                                            7
Name: 26, dtype: object
17102
Unnamed: 0                                     107
key                                            113
uid                                            113
ctr                                 [23790, 35985]
coord            [[23765 35960]\r\n [23815 36010]]
lbl                                              2
guid          9578cba9-4f0f-4504-9b9c-a322e5cda153
subcl                                            5
Name: 27, dtype: object
23790
Unnamed: 0                                     179
key                                           1387
uid                                           1387
ctr                                  [8466, 32091]
coord            [[ 8441 32066]\r\n [ 8491 32116]]
lbl                                              2
guid          3d165965-5ae6-4897-84a1-7b071f2d1025
subcl                                            6
Name: 28, dtype: object
8466
Unnamed: 0                                      57
key                                             59
uid                                             59
ctr                                 [32728, 26173]
coord            [[32703 26148]\r\n [32753 26198]]
lbl                                              2
guid          58d9937d-3b0d-4949-9095-82f9c7724d5b
subcl                                            5
Name: 29, dtype: object
32728
Unnamed: 0                                     115
key                                            121
uid                                            121
ctr                                  [6735, 36073]
coord            [[ 6710 36048]\r\n [ 6760 36098]]
lbl                                              2
guid          e86e1720-eb69-495d-bcc6-01e7b4cb879d
subcl                                            4
Name: 30, dtype: object
6735
Unnamed: 0                                     156
key                                            168
uid                                            168
ctr                                 [33107, 50474]
coord            [[33082 50449]\r\n [33132 50499]]
lbl                                              2
guid          b3b87c92-64f6-4133-9ee9-6bbb469fa56d
subcl                                            6
Name: 31, dtype: object
33107
Unnamed: 0                                     159
key                                            171
uid                                            171
ctr                                 [30389, 51321]
coord            [[30364 51296]\r\n [30414 51346]]
lbl                                              2
guid          e962a299-5372-4926-a332-4d954313af97
subcl                                            4
Name: 32, dtype: object
30389
Unnamed: 0                                     160
key                                            172
uid                                            172
ctr                                 [34634, 52144]
coord            [[34609 52119]\r\n [34659 52169]]
lbl                                              2
guid          124e0380-4a0e-4694-a5ce-9d30ee34a17e
subcl                                            4
Name: 33, dtype: object
34634
Unnamed: 0                                     150
key                                            162
uid                                            162
ctr                                 [32764, 48674]
coord            [[32739 48649]\r\n [32789 48699]]
lbl                                              2
guid          f7383f3a-ed2d-4fb9-bc50-2f93340d14c3
subcl                                            3
Name: 34, dtype: object
32764
Unnamed: 0                                     149
key                                            161
uid                                            161
ctr                                 [32911, 48989]
coord            [[32886 48964]\r\n [32936 49014]]
lbl                                              2
guid          24ec2bb8-b848-431b-a5ca-11952b4c388d
subcl                                            7
Name: 35, dtype: object
32911
Unnamed: 0                                     147
key                                            159
uid                                            159
ctr                                 [30237, 48493]
coord            [[30212 48468]\r\n [30262 48518]]
lbl                                              2
guid          9dcdde06-da45-419e-b152-8b54d02a4e26
subcl                                            7
Name: 36, dtype: object
30237
Unnamed: 0                                     143
key                                            155
uid                                            155
ctr                                 [34567, 45582]
coord            [[34542 45557]\r\n [34592 45607]]
lbl                                              2
guid          d5199783-ba31-4564-996e-56020133ab01
subcl                                            3
Name: 37, dtype: object
34567
Unnamed: 0                                     142
key                                            154
uid                                            154
ctr                                 [32861, 45897]
coord            [[32836 45872]\r\n [32886 45922]]
lbl                                              2
guid          4f726075-86ac-411e-b2e8-49430a860af0
subcl                                            7
Name: 38, dtype: object
32861
Unnamed: 0                                     141
key                                            153
uid                                            153
ctr                                 [39061, 43797]
coord            [[39036 43772]\r\n [39086 43822]]
lbl                                              2
guid          a36ab972-fe45-40f8-a84f-c37d5aed8c4e
subcl                                            6
Name: 39, dtype: object
39061
Unnamed: 0                                     140
key                                            152
uid                                            152
ctr                                 [37117, 42070]
coord            [[37092 42045]\r\n [37142 42095]]
lbl                                              2
guid          8dc11cfa-05bb-4a81-b462-daa5a0698ae7
subcl                                            7
Name: 40, dtype: object
37117
Unnamed: 0                                     138
key                                            149
uid                                            149
ctr                                 [40985, 40030]
coord            [[40960 40005]\r\n [41010 40055]]
lbl                                              2
guid          924ee197-3f86-461e-bd5f-4f97fb311ec5
subcl                                            7
Name: 41, dtype: object
40985
Unnamed: 0                                     137
key                                            148
uid                                            148
ctr                                 [33887, 40563]
coord            [[33862 40538]\r\n [33912 40588]]
lbl                                              2
guid          b2d6f36b-c456-4ee4-9285-d3e9fd21e730
subcl                                            7
Name: 42, dtype: object
33887
Unnamed: 0                                     135
key                                            145
uid                                            145
ctr                                 [39607, 39511]
coord            [[39582 39486]\r\n [39632 39536]]
lbl                                              2
guid          d7610fcd-5454-4a04-a9c1-eca9e66cd6da
subcl                                            7
Name: 43, dtype: object
39607
Unnamed: 0                                     133
key                                            143
uid                                            143
ctr                                 [37772, 39661]
coord            [[37747 39636]\r\n [37797 39686]]
lbl                                              2
guid          1fd1dc45-45b5-4efa-a593-779cdd166ed3
subcl                                            7
Name: 44, dtype: object
37772
Unnamed: 0                                     132
key                                            142
uid                                            142
ctr                                 [37825, 39899]
coord            [[37800 39874]\r\n [37850 39924]]
lbl                                              2
guid          b9430f75-4a6e-49b6-94b2-bf0dbcf81027
subcl                                            7
Name: 45, dtype: object
37825
Unnamed: 0                                     173
key                                           1379
uid                                           1379
ctr                                 [28218, 29577]
coord            [[28193 29552]\r\n [28243 29602]]
lbl                                              2
guid          e5500032-4a6b-4701-8e0f-17fdcabfea54
subcl                                            7
Name: 47, dtype: object
28218
Unnamed: 0                                     127
key                                            136
uid                                            136
ctr                                 [38546, 38734]
coord            [[38521 38709]\r\n [38571 38759]]
lbl                                              2

"\n    for k in DB.annotations.keys():   #FSL annotations should be used here\n\n        anno = DB.annotations[k]\n\n        if anno.deleted or anno.annotationType != AnnotationType.SPOT:\n            continue\n        coord_x = anno.x1\n        coord_y = anno.y1\n\n        lu_x = int(coord_x - int(patchSize/2))\n        lu_y = int(coord_y - int(patchSize/2))\n        img = np.array(slide.read_region(location=(lu_x, lu_y), level=0, size=(patchSize, patchSize)))\n        img = cv2.cvtColor(img, cv2.COLOR_RGBA2BGR)\n\n\n        istest = 'train/' if str(slideid) not in test_slides[sys.argv[1]] else 'test/'\n        if (anno.agreedClass ==2):\n            cv2.imwrite('images/Mitosis/%d.png' % k, img)\n            system(f'ln -s ../../../images/Mitosis/{k}.png Data_CMC{sys.argv[1]}/'+istest+'Mitosis/%d.png' %k)\n\n        if (anno.agreedClass==1):\n            cv2.imwrite('images/Nonmitosis/%d.png' % k, img)\n            system(f'ln -s ../../../images/Nonmitosis/{k}.png Data_CMC{sys.argv[1]}/'+istest+'Nonmitosis/%d.png' %k)\n            "

In [ ]:
!pwd

/content/drive/MyDrive/MITOS_WSI_CMC/databases

In [25]:
!ls

0.png	32.png	55.png	78.png
10.png	33.png	56.png	79.png
11.png	34.png	57.png	7.png
12.png	35.png	58.png	80.png
13.png	36.png	59.png	81.png
14.png	37.png	5.png	82.png
15.png	38.png	60.png	83.png
16.png	39.png	61.png	84.png
17.png	3.png	62.png	85.png
18.png	40.png	63.png	86.png
19.png	41.png	64.png	87.png
1.png	42.png	65.png	88.png
20.png	43.png	66.png	89.png
21.png	44.png	67.png	8.png
22.png	45.png	68.png	9.png
23.png	46.png	69.png	databaseStatistics.ipynb
24.png	47.png	6.png	Data_CMC-f
25.png	48.png	70.png	MITOS_WSI_CMC_COADEL_TR.sqlite
26.png	49.png	71.png	MITOS_WSI_CMC_CODAEL_TR_ROI.sqlite
27.png	4.png	72.png	MITOS_WSI_CMC_MEL.sqlite
28.png	50.png	73.png	MITOS_WSI_CMC_ODAEL_TR.sqlite
29.png	51.png	74.png	subclass_patches
2.png	52.png	75.png	TUPAC_alternativeLabels_augmented_training.sqlite
30.png	53.png	76.png	TUPAC.sqlite
31.png	54.png	77.png	TUPAC_stitched.sqlite